-- supabase/migrations/20260719040000_revoke_public_execute_funciones.sql

revoke execute on function public.convertir_lead_a_cliente(uuid, text, text) from public;
revoke execute on function public.fn_archivar_cerrados() from public;
revoke execute on function public.fn_bump_lead_actividad() from public;
revoke execute on function public.fn_conteo_tickets_cliente(uuid) from public;
revoke execute on function public.fn_gestionar_cierre_leads() from public;
revoke execute on function public.fn_gestionar_cierre_tickets() from public;
revoke execute on function public.fn_gestionar_cierre_tickets_post_venta() from public;
revoke execute on function public.fn_incrementar_version() from public;
revoke execute on function public.fn_notificar_capacitacion_asignada() from public;
revoke execute on function public.fn_notificar_citas_vencidas() from public;
revoke execute on function public.fn_notificar_lead_asignado() from public;
revoke execute on function public.fn_notificar_leads_inactivos() from public;
revoke execute on function public.fn_notificar_tarea_asignada() from public;
revoke execute on function public.fn_notificar_tareas_vencidas() from public;
revoke execute on function public.fn_notificar_ticket_asignado() from public;
revoke execute on function public.fn_notificar_tickets_post_venta_vencidos() from public;
revoke execute on function public.fn_resetear_notificada_vencida() from public;
revoke execute on function public.fn_resetear_notificada_vencida_citas() from public;
revoke execute on function public.fn_resetear_notificada_vencida_tpv() from public;
revoke execute on function public.fn_resetear_notificado_inactividad() from public;
revoke execute on function public.handle_new_user() from public;
revoke execute on function public.has_permission(uuid, text, text) from public;
revoke execute on function public.mis_features() from public;
revoke execute on function public.mis_widgets() from public;
revoke execute on function public.permisos_efectivos_usuario(uuid) from public;
revoke execute on function public.proteger_cambio_rol() from public;
revoke execute on function public.registrar_auditoria() from public;
revoke execute on function public.registrar_historial_estado() from public;
revoke execute on function public.rls_auto_enable() from public;
revoke execute on function public.usuarios_por_rol(text) from public;

grant execute on function public.has_permission(uuid, text, text) to authenticated;
grant execute on function public.mis_features() to authenticated;
grant execute on function public.mis_widgets() to authenticated;
grant execute on function public.permisos_efectivos_usuario(uuid) to authenticated;
grant execute on function public.usuarios_por_rol(text) to authenticated;
grant execute on function public.convertir_lead_a_cliente(uuid, text, text) to authenticated;
grant execute on function public.fn_conteo_tickets_cliente(uuid) to authenticated;
